[package]
name = "sort"
kind = "lib"
unsafe = false

[dependencies]
array = { git = "https://github.com/bats-lang/array.git", version = "main" }
arith = { git = "https://github.com/bats-lang/arith.git", version = "main" }
